name: kafka-connect-upgrade-tests
lang: java
lang_version: 8
github:
  enable: true
  repo_name: confluentinc/kafka-connect-upgrade-tests
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  cve_scan: true
  extra_deploy_args: "-Pjenkins"
  extra_build_args: "-Pjenkins"
  run_pint_merge: true
code_artifact:
  enable: true
  package_paths:
    - maven-snapshots/maven/io.confluent/kafka-connect-upgrade-tests
