name: kafka-connect-upgrade-tests
lang: java
lang_version: 8
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  cve_scan: true
  extra_deploy_args: "-Pjenkins"
  extra_build_args: "-Pjenkins"
  run_pint_merge: true